// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.26.1
// source: chronosdb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChronosDB_Execute_FullMethodName = "/chronosdb.ChronosDB/Execute"
	ChronosDB_Import_FullMethodName  = "/chronosdb.ChronosDB/Import"
)

// ChronosDBClient is the client API for ChronosDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChronosDBClient interface {
	Execute(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
	Import(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportRecord, ImportSummary], error)
}

type chronosDBClient struct {
	cc grpc.ClientConnInterface
}

func NewChronosDBClient(cc grpc.ClientConnInterface) ChronosDBClient {
	return &chronosDBClient{cc}
}

func (c *chronosDBClient) Execute(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChronosDB_ServiceDesc.Streams[0], ChronosDB_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChronosDB_ExecuteClient = grpc.ServerStreamingClient[QueryResponse]

func (c *chronosDBClient) Import(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportRecord, ImportSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChronosDB_ServiceDesc.Streams[1], ChronosDB_Import_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportRecord, ImportSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChronosDB_ImportClient = grpc.ClientStreamingClient[ImportRecord, ImportSummary]

// ChronosDBServer is the server API for ChronosDB service.
// All implementations must embed UnimplementedChronosDBServer
// for forward compatibility.
type ChronosDBServer interface {
	Execute(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error
	Import(grpc.ClientStreamingServer[ImportRecord, ImportSummary]) error
	mustEmbedUnimplementedChronosDBServer()
}

// UnimplementedChronosDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChronosDBServer struct{}

func (UnimplementedChronosDBServer) Execute(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedChronosDBServer) Import(grpc.ClientStreamingServer[ImportRecord, ImportSummary]) error {
	return status.Error(codes.Unimplemented, "method Import not implemented")
}
func (UnimplementedChronosDBServer) mustEmbedUnimplementedChronosDBServer() {}
func (UnimplementedChronosDBServer) testEmbeddedByValue()                   {}

// UnsafeChronosDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChronosDBServer will
// result in compilation errors.
type UnsafeChronosDBServer interface {
	mustEmbedUnimplementedChronosDBServer()
}

func RegisterChronosDBServer(s grpc.ServiceRegistrar, srv ChronosDBServer) {
	// If the following call panics, it indicates UnimplementedChronosDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChronosDB_ServiceDesc, srv)
}

func _ChronosDB_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChronosDBServer).Execute(m, &grpc.GenericServerStream[QueryRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChronosDB_ExecuteServer = grpc.ServerStreamingServer[QueryResponse]

func _ChronosDB_Import_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChronosDBServer).Import(&grpc.GenericServerStream[ImportRecord, ImportSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChronosDB_ImportServer = grpc.ClientStreamingServer[ImportRecord, ImportSummary]

// ChronosDB_ServiceDesc is the grpc.ServiceDesc for ChronosDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChronosDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chronosdb.ChronosDB",
	HandlerType: (*ChronosDBServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _ChronosDB_Execute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Import",
			Handler:       _ChronosDB_Import_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "chronosdb.proto",
}
