// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: chronosdb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	QueryText     string                 `protobuf:"bytes,2,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	Parameters    map[string]*Value      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_chronosdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chronosdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_chronosdb_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *QueryRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *QueryRequest) GetParameters() map[string]*Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*QueryResponse_Row
	//	*QueryResponse_Error
	Result        isQueryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_chronosdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chronosdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_chronosdb_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetResult() isQueryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryResponse) GetRow() *Row {
	if x != nil {
		if x, ok := x.Result.(*QueryResponse_Row); ok {
			return x.Row
		}
	}
	return nil
}

func (x *QueryResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*QueryResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isQueryResponse_Result interface {
	isQueryResponse_Result()
}

type QueryResponse_Row struct {
	Row *Row `protobuf:"bytes,1,opt,name=row,proto3,oneof"`
}

type QueryResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QueryResponse_Row) isQueryResponse_Result() {}

func (*QueryResponse_Error) isQueryResponse_Result() {}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_chronosdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_chronosdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_chronosdb_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StringValue
	//	*Value_NumberValue
	//	*Value_BoolValue
	//	*Value_TimestampValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_chronosdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_chronosdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_chronosdb_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetTimestampValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return ""
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_TimestampValue struct {
	TimestampValue string `protobuf:"bytes,4,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_NumberValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_TimestampValue) isValue_Kind() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_chronosdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_chronosdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_chronosdb_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImportRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Properties    map[string]*Value      `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ValidFrom     string                 `protobuf:"bytes,3,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       string                 `protobuf:"bytes,4,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRecord) Reset() {
	*x = ImportRecord{}
	mi := &file_chronosdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRecord) ProtoMessage() {}

func (x *ImportRecord) ProtoReflect() protoreflect.Message {
	mi := &file_chronosdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRecord.ProtoReflect.Descriptor instead.
func (*ImportRecord) Descriptor() ([]byte, []int) {
	return file_chronosdb_proto_rawDescGZIP(), []int{5}
}

func (x *ImportRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ImportRecord) GetProperties() map[string]*Value {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ImportRecord) GetValidFrom() string {
	if x != nil {
		return x.ValidFrom
	}
	return ""
}

func (x *ImportRecord) GetValidTo() string {
	if x != nil {
		return x.ValidTo
	}
	return ""
}

type ImportSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodesCreated  int64                  `protobuf:"varint,1,opt,name=nodes_created,json=nodesCreated,proto3" json:"nodes_created,omitempty"`
	EdgesCreated  int64                  `protobuf:"varint,2,opt,name=edges_created,json=edgesCreated,proto3" json:"edges_created,omitempty"`
	Errors        int64                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSummary) Reset() {
	*x = ImportSummary{}
	mi := &file_chronosdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSummary) ProtoMessage() {}

func (x *ImportSummary) ProtoReflect() protoreflect.Message {
	mi := &file_chronosdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSummary.ProtoReflect.Descriptor instead.
func (*ImportSummary) Descriptor() ([]byte, []int) {
	return file_chronosdb_proto_rawDescGZIP(), []int{6}
}

func (x *ImportSummary) GetNodesCreated() int64 {
	if x != nil {
		return x.NodesCreated
	}
	return 0
}

func (x *ImportSummary) GetEdgesCreated() int64 {
	if x != nil {
		return x.EdgesCreated
	}
	return 0
}

func (x *ImportSummary) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

var File_chronosdb_proto protoreflect.FileDescriptor

const file_chronosdb_proto_rawDesc = "" +
	"\n" +
	"\x0fchronosdb.proto\x12\tchronosdb\"\xe3\x01\n" +
	"\fQueryRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1d\n" +
	"\n" +
	"query_text\x18\x02 \x01(\tR\tqueryText\x12G\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2'.chronosdb.QueryRequest.ParametersEntryR\n" +
	"parameters\x1aO\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.chronosdb.ValueR\x05value:\x028\x01\"g\n" +
	"\rQueryResponse\x12\"\n" +
	"\x03row\x18\x01 \x01(\v2\x0e.chronosdb.RowH\x00R\x03row\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x10.chronosdb.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x86\x01\n" +
	"\x03Row\x122\n" +
	"\x06fields\x18\x01 \x03(\v2\x1a.chronosdb.Row.FieldsEntryR\x06fields\x1aK\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.chronosdb.ValueR\x05value:\x028\x01\"\xa5\x01\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12)\n" +
	"\x0ftimestamp_value\x18\x04 \x01(\tH\x00R\x0etimestampValueB\x06\n" +
	"\x04kind\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf6\x01\n" +
	"\fImportRecord\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12G\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2'.chronosdb.ImportRecord.PropertiesEntryR\n" +
	"properties\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x03 \x01(\tR\tvalidFrom\x12\x19\n" +
	"\bvalid_to\x18\x04 \x01(\tR\avalidTo\x1aO\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.chronosdb.ValueR\x05value:\x028\x01\"q\n" +
	"\rImportSummary\x12#\n" +
	"\rnodes_created\x18\x01 \x01(\x03R\fnodesCreated\x12#\n" +
	"\redges_created\x18\x02 \x01(\x03R\fedgesCreated\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x03R\x06errors2\x8a\x01\n" +
	"\tChronosDB\x12>\n" +
	"\aExecute\x12\x17.chronosdb.QueryRequest\x1a\x18.chronosdb.QueryResponse0\x01\x12=\n" +
	"\x06Import\x12\x17.chronosdb.ImportRecord\x1a\x18.chronosdb.ImportSummary(\x01B%Z#github.com/emkwambe/chronosdb/protob\x06proto3"

var (
	file_chronosdb_proto_rawDescOnce sync.Once
	file_chronosdb_proto_rawDescData []byte
)

func file_chronosdb_proto_rawDescGZIP() []byte {
	file_chronosdb_proto_rawDescOnce.Do(func() {
		file_chronosdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chronosdb_proto_rawDesc), len(file_chronosdb_proto_rawDesc)))
	})
	return file_chronosdb_proto_rawDescData
}

var file_chronosdb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chronosdb_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: chronosdb.QueryRequest
	(*QueryResponse)(nil), // 1: chronosdb.QueryResponse
	(*Row)(nil),           // 2: chronosdb.Row
	(*Value)(nil),         // 3: chronosdb.Value
	(*Error)(nil),         // 4: chronosdb.Error
	(*ImportRecord)(nil),  // 5: chronosdb.ImportRecord
	(*ImportSummary)(nil), // 6: chronosdb.ImportSummary
	nil,                   // 7: chronosdb.QueryRequest.ParametersEntry
	nil,                   // 8: chronosdb.Row.FieldsEntry
	nil,                   // 9: chronosdb.ImportRecord.PropertiesEntry
}
var file_chronosdb_proto_depIdxs = []int32{
	7,  // 0: chronosdb.QueryRequest.parameters:type_name -> chronosdb.QueryRequest.ParametersEntry
	2,  // 1: chronosdb.QueryResponse.row:type_name -> chronosdb.Row
	4,  // 2: chronosdb.QueryResponse.error:type_name -> chronosdb.Error
	8,  // 3: chronosdb.Row.fields:type_name -> chronosdb.Row.FieldsEntry
	9,  // 4: chronosdb.ImportRecord.properties:type_name -> chronosdb.ImportRecord.PropertiesEntry
	3,  // 5: chronosdb.QueryRequest.ParametersEntry.value:type_name -> chronosdb.Value
	3,  // 6: chronosdb.Row.FieldsEntry.value:type_name -> chronosdb.Value
	3,  // 7: chronosdb.ImportRecord.PropertiesEntry.value:type_name -> chronosdb.Value
	0,  // 8: chronosdb.ChronosDB.Execute:input_type -> chronosdb.QueryRequest
	5,  // 9: chronosdb.ChronosDB.Import:input_type -> chronosdb.ImportRecord
	1,  // 10: chronosdb.ChronosDB.Execute:output_type -> chronosdb.QueryResponse
	6,  // 11: chronosdb.ChronosDB.Import:output_type -> chronosdb.ImportSummary
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_chronosdb_proto_init() }
func file_chronosdb_proto_init() {
	if File_chronosdb_proto != nil {
		return
	}
	file_chronosdb_proto_msgTypes[1].OneofWrappers = []any{
		(*QueryResponse_Row)(nil),
		(*QueryResponse_Error)(nil),
	}
	file_chronosdb_proto_msgTypes[3].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_TimestampValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chronosdb_proto_rawDesc), len(file_chronosdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chronosdb_proto_goTypes,
		DependencyIndexes: file_chronosdb_proto_depIdxs,
		MessageInfos:      file_chronosdb_proto_msgTypes,
	}.Build()
	File_chronosdb_proto = out.File
	file_chronosdb_proto_goTypes = nil
	file_chronosdb_proto_depIdxs = nil
}
